#!/bin/bash

echo "Starting of Job"
/home/jinh574/hive/bin/hive -e "INSERT OVERWRITE TABLE mention_count PARTITION (candidate = '1') SELECT a.presstype AS presstype, a.count AS word_count, b.count AS total_count, a.count/b.count AS avg_count FROM (SELECT presstype, count(1) AS count FROM (logs LATERAL VIEW explode(split(contents, ' ')) exploded_table AS word) WHERE word LIKE '%문재인%' OR word LIKE '%문 후보%' GROUP BY presstype) a JOIN (SELECT presstype, count(1) AS count FROM logs GROUP BY presstype) b ON (a.presstype = b.presstype);
INSERT OVERWRITE TABLE mention_count PARTITION (candidate = '2') SELECT a.presstype AS presstype, a.count AS word_count, b.count AS total_count, a.count/b.count AS avg_count FROM (SELECT presstype, count(1) AS count FROM (logs LATERAL VIEW explode(split(contents, ' ')) exploded_table AS word) WHERE word LIKE '%홍준표%' OR word LIKE '%홍 후보%' GROUP BY presstype) a JOIN (SELECT presstype, count(1) AS count FROM logs GROUP BY presstype) b ON (a.presstype = b.presstype);
INSERT OVERWRITE TABLE mention_count PARTITION (candidate = '3') SELECT a.presstype AS presstype, a.count AS word_count, b.count AS total_count, a.count/b.count AS avg_count FROM (SELECT presstype, count(1) AS count FROM (logs LATERAL VIEW explode(split(contents, ' ')) exploded_table AS word) WHERE word LIKE '%안철수%' OR word LIKE '%안 후보%' GROUP BY presstype) a JOIN (SELECT presstype, count(1) AS count FROM logs GROUP BY presstype) b ON (a.presstype = b.presstype);
INSERT OVERWRITE TABLE mention_count PARTITION (candidate = '4') SELECT a.presstype AS presstype, a.count AS word_count, b.count AS total_count, a.count/b.count AS avg_count FROM (SELECT presstype, count(1) AS count FROM (logs LATERAL VIEW explode(split(contents, ' ')) exploded_table AS word) WHERE word LIKE '%유승민%' OR word LIKE '%유 후보%' GROUP BY presstype) a JOIN (SELECT presstype, count(1) AS count FROM logs GROUP BY presstype) b ON (a.presstype = b.presstype);
INSERT OVERWRITE TABLE mention_count PARTITION (candidate = '5') SELECT a.presstype AS presstype, a.count AS word_count, b.count AS total_count, a.count/b.count AS avg_count FROM (SELECT presstype, count(1) AS count FROM (logs LATERAL VIEW explode(split(contents, ' ')) exploded_table AS word) WHERE word LIKE '%심상정%' OR word LIKE '%심 후보%' GROUP BY presstype) a JOIN (SELECT presstype, count(1) AS count FROM logs GROUP BY presstype) b ON (a.presstype = b.presstype);
INSERT OVERWRITE TABLE mention_count PARTITION (candidate = '6') SELECT a.presstype AS presstype, a.count AS word_count, b.count AS total_count, a.count/b.count AS avg_count FROM (SELECT presstype, count(1) AS count FROM (logs LATERAL VIEW explode(split(contents, ' ')) exploded_table AS word) WHERE word LIKE '%조원진%' OR word LIKE '%조 후보%' GROUP BY presstype) a JOIN (SELECT presstype, count(1) AS count FROM logs GROUP BY presstype) b ON (a.presstype = b.presstype);
INSERT OVERWRITE TABLE mention_count PARTITION (candidate = '7') SELECT a.presstype AS presstype, a.count AS word_count, b.count AS total_count, a.count/b.count AS avg_count FROM (SELECT presstype, count(1) AS count FROM (logs LATERAL VIEW explode(split(contents, ' ')) exploded_table AS word) WHERE word LIKE '%오영국%' OR word LIKE '%오 후보%' GROUP BY presstype) a JOIN (SELECT presstype, count(1) AS count FROM logs GROUP BY presstype) b ON (a.presstype = b.presstype);
INSERT OVERWRITE TABLE mention_count PARTITION (candidate = '8') SELECT a.presstype AS presstype, a.count AS word_count, b.count AS total_count, a.count/b.count AS avg_count FROM (SELECT presstype, count(1) AS count FROM (logs LATERAL VIEW explode(split(contents, ' ')) exploded_table AS word) WHERE word LIKE '%장성민%' OR word LIKE '%장 후보%' GROUP BY presstype) a JOIN (SELECT presstype, count(1) AS count FROM logs GROUP BY presstype) b ON (a.presstype = b.presstype);
INSERT OVERWRITE TABLE mention_count PARTITION (candidate = '9') SELECT a.presstype AS presstype, a.count AS word_count, b.count AS total_count, a.count/b.count AS avg_count FROM (SELECT presstype, count(1) AS count FROM (logs LATERAL VIEW explode(split(contents, ' ')) exploded_table AS word) WHERE word LIKE '%이재오%' OR word LIKE '%이 후보%' GROUP BY presstype) a JOIN (SELECT presstype, count(1) AS count FROM logs GROUP BY presstype) b ON (a.presstype = b.presstype);
INSERT OVERWRITE TABLE mention_count PARTITION (candidate = '10') SELECT a.presstype AS presstype, a.count AS word_count, b.count AS total_count, a.count/b.count AS avg_count FROM (SELECT presstype, count(1) AS count FROM (logs LATERAL VIEW explode(split(contents, ' ')) exploded_table AS word) WHERE word LIKE '%김선동%' OR word LIKE '%김 후보%' GROUP BY presstype) a JOIN (SELECT presstype, count(1) AS count FROM logs GROUP BY presstype) b ON (a.presstype = b.presstype);
INSERT OVERWRITE TABLE mention_count PARTITION (candidate = '12') SELECT a.presstype AS presstype, a.count AS word_count, b.count AS total_count, a.count/b.count AS avg_count FROM (SELECT presstype, count(1) AS count FROM (logs LATERAL VIEW explode(split(contents, ' ')) exploded_table AS word) WHERE word LIKE '%이경희%' GROUP BY presstype) a JOIN (SELECT presstype, count(1) AS count FROM logs GROUP BY presstype) b ON (a.presstype = b.presstype);
INSERT OVERWRITE TABLE mention_count PARTITION (candidate = '14') SELECT a.presstype AS presstype, a.count AS word_count, b.count AS total_count, a.count/b.count AS avg_count FROM (SELECT presstype, count(1) AS count FROM (logs LATERAL VIEW explode(split(contents, ' ')) exploded_table AS word) WHERE word LIKE '%윤홍식%' OR word LIKE '%윤 후보%' GROUP BY presstype) a JOIN (SELECT presstype, count(1) AS count FROM logs GROUP BY presstype) b ON (a.presstype = b.presstype);
INSERT OVERWRITE TABLE mention_count PARTITION (candidate = '15') SELECT a.presstype AS presstype, a.count AS word_count, b.count AS total_count, a.count/b.count AS avg_count FROM (SELECT presstype, count(1) AS count FROM (logs LATERAL VIEW explode(split(contents, ' ')) exploded_table AS word) WHERE word LIKE '%김민찬%' GROUP BY presstype) a JOIN (SELECT presstype, count(1) AS count FROM logs GROUP BY presstype) b ON (a.presstype = b.presstype);" > /dev/null 2>&1
/home/jinh574/sqoop-1.4.6/bin/sqoop --options-file /home/jinh574/mysqoop.txt > /dev/null 2>&1
echo "Script ends."
